include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # print() 사용을 피하도록 권장
    avoid_print: true

    # 작은 따옴표 사용을 선호
    prefer_single_quotes: true

    # 가능한 곳에서는 const 생성자를 사용하도록 권장
    prefer_const_constructors: true

    # 코드에서 주석을 추가하도록 유도하는 규칙
    comment_references: true

    # 긴 코드 라인에서 마지막에 콤마를 추가하도록 유도하여 주석을 추가할 공간 확보
    require_trailing_commas: true

    # 메서드나 클래스에 설명을 추가할 때 필수로 주석을 달도록 유도
    public_member_api_docs: true

    # `await`와 `async`가 사용되지 않은 곳에서는 async/await 패턴을 강제하도록 유도
    await_only_futures: true

    # 상수를 위한 대문자 사용을 강제
    constant_identifier_names: true

    # 숫자 리터럴에서 접미사를 붙이지 않도록 유도
    prefer_int_literals: true
